### ISSUE TITLE
wrong path for model optimizer

### ISSUE THREAD

**Issue by srinidhikasagar** [intel-iot-devkit/store-traffic-monitor#3]
in setup.sh file - reference to the mobilenet-ssd.caffemodel is wrong. 2019 open vino refers to
/opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/public/mobilenet-ssd/mobilenet-ssd.caffemodel

Pls change accordingly.

**Comment by MandipJ** [comment]
@srinidhikasagar 
Which version of OpenVINO are you using, OpenVINO 2019 R2 or OpenvVINO 2019 R3?

**Comment by srinidhikasagar** [comment]
It is 2019 R3. l_openvino_toolkit_p_2019.3.376 is the one which I have downloaded.

**Comment by MandipJ** [comment]
As mentioned in the Readme, the application is using OpenVINO 2019 R2. So the path is correct for R2.
In OpenVINO R3, path to models has been changed.
